(()=>{'use strict';
const data=JSON.parse(document.getElementById('robust-data').textContent);
const pageSize = 50;
const el=id=>document.getElementById('robust-'+id);
let all=[...data.totals,...data.buckets]; const catalog=new Map(data.reasons.map(r=>[r.key,r]));
const methods={AtQuote:'仅贴买卖价',Midpoint:'中间价法',MidpointTick:'中间价＋逐笔涨跌'};
const quality={LOCAL_INCOMPLETE:'本地记录不完整',PARTIAL_BUCKET:'未完整观察这个桶',NON_REALTIME:'包含非实时行情',OBSERVATION_GAP:'观察曾中断',CLOCK_JUMP:'时钟发生跳变',RECONCILIATION_BOUNDARY:'跨桶累计量不能精确分摊',RECONCILIATION_DIFFERENCE:'成交明细与累计量存在差额',PREMIUM_DIFFERENCE:'累计权利金存在差额（可能含均价精度影响）',NO_COMPARISON_BASELINE:'缺少累计量比较基线',INSUFFICIENT_SAMPLE:'少于 30 笔可识别成交'};
const help={
 outside:['报价外成交特殊处理','默认关闭。开启后，仅对原本属于 U15 的成交重新分类：成交价高于 Ask 判买，低于 Bid 判卖。比较的是每单位成交价，不是整笔权利金。\n报价缺失、过龄、延迟或时间歧义等限制仍保留；每个时间候选先单独重新判断，再计算一致性。此规则是实验假设，不是准确率提升保证。'.replace(/\n/g,'\n')],
 scope:['成交口径','常规成交：使用接口的常规成交回报（375）。\n全部成交回报：使用另一种成交口径（233）。\n两种口径各自分析，不能相加，否则可能重复计算。名称不保证接口提供了市场上的每一笔成交。'],
 method:['三种分类方法','仅贴买卖价：恰好等于卖价判买，等于买价判卖；价差内部未知。\n中间价法：有效价差内，高于中间价判买，低于中间价判卖，正中间归 Mid 中性（原 U17）。\n中间价＋逐笔涨跌：先用中间价法，只有正中间成交才用近期逐笔涨跌补判（MIDPOINT_TICK）。前笔与最近非零变化均须符合 5 秒连续性规则。\n买卖报价相同归 Mid 中性（原 U11）。报价外成交可用单独开关处理，默认仍为未知。三种方法可选择同样的时间对齐方式。'],
 alignment:['分类方法 ≠ 时间对齐','分类方法决定怎样判断买卖；时间对齐决定使用哪一份报价。\n接收时最新报价：在收到成交之前最后收到的报价，可比较不同报价年龄阈值。\n源时间附近：按成交源时间加指定 Δ，查找当时已收到的历史报价。\n多时间候选一致：比较最新报价与所有时间可行的源候选（−250、−100、0、+100、+250 毫秒）；至少两个源候选可行，且所有必要候选都能判断、方向相同才分类。\n晚于成交接收时刻的候选不用；同一报价状态不是独立证据。偏移是假设，不是实测延迟。逐笔补判的一致也可能共同依赖同一个涨跌方向。'],
 premium:['权利金构成','每笔权利金 = 成交价 × 成交数量 × 合约乘数。横条依次是估计买方、估计卖方、Mid 中性、未知。\n只包含程序接纳的已观察成交明细，不把缺失的累计增量按最后一笔方向补齐。\n买卖指期权成交侧，不等于标的上涨或下跌。'],
 tendency:['倾向：已分类部分偏哪边？','倾向 =（买方权利金 − 卖方权利金）÷（买方权利金 + 卖方权利金）。\n+100%：已分类部分全偏买；−100%：全偏卖；0%：两侧相等。没有已分类权利金时显示“—”。\n例：买方 60、卖方 30、未知 10，倾向为 +33.3%。它不是上涨概率，也没有包含未知部分的方向。'],
 coverage:['分类覆盖：判断了多少？','覆盖 =（买方 + 卖方 + Mid）÷（买方 + 卖方 + Mid + 未知），按权利金计算，不是笔数。\n例：买方 60、卖方 30、未知 10，覆盖 90%。\n分母是已观察明细，不是市场全部成交；高覆盖不代表高准确率。Mid 算已分类但不算方向；每行另列买卖方向覆盖 =（买方 + 卖方）÷ 总量。'],
 bounds:['未知边界：未知能否推翻结论？','假设已分类方向全对：把未知全部归卖方，得到下界；全部归买方，得到上界。\n下界 =（买方 − 卖方 − 未知）÷ 总量\n上界 =（买方 − 卖方 + 未知）÷ 总量\n例如 [−20.06%, +84.37%]：仅未知部分就足以让整体从偏卖变成偏买。跨零时不应断言整体方向。\nMid 按中性贡献零净值并计入总量，不作为未知分配。此边界以 Mid 确为中性为前提。这不是统计置信区间，不含已分类误判或接口未提供的成交。'],
 timing:['时间敏感性：换一份报价会变吗？','范围：当前分类方法在“最新报价（无年龄上限）＋五个源时间偏移”六种场景中，有已分类数据的桶倾向最小值至最大值。不是未知边界，也不是置信区间。各场景分类覆盖可能不同；无可计算倾向的场景不计入范围，不能因此称其稳定。\n冲突占比：同一笔成交在可行时间候选中既被判买又被判卖的权利金 ÷ 全部已观察权利金。即使其他候选未知，也计冲突；每笔最多计一次。\n不同于在桶汇总后观察正负变化。0% 冲突也可能因为大部分候选无法判断，不能视为高可信。'],
 unknown:['未知原因：为什么不能分类？','横条分母是未知权利金，各色段相加 100%；点击色段查看编号、原因、金额、笔数及占全部权利金的比例。\n固定编号和颜色跨方法、品种、时间桶一致。每筆按规则优先级只计一个主原因，不重复累加。\n一致性模式下，时间候选不足优先，其次买卖冲突，再次候选不能判断；全部候选都为 Mid 时归 Mid，Mid 与买卖混合为 U26。候选中的具体原因留在逐笔证据。\n基线、重复、倒序等被排除事件不混进未知；没有未知时不画满条。'],
 tolerance:['抗误判余量：还能承受多少判反？','先把未知全部算到不利一侧，再问：多少已分类权利金被判反，当前方向就会消失？\n余量 = max(0, |买方 − 卖方| − 未知) ÷（2 × 总量）。\n例：买方 60、卖方 30、未知 10。未知全归卖方后仍领先 20；每 1 单位买方被改判卖方，会损失 2 单位净优势。10 单位判反后打平，余量为 10%。\n恰好到达临界值不算通过。0% 表示未知本身已能推翻方向。它不是概率或实测误判率。质量不足时只提供算术参考。']
};
let page=0;
const pct=x=>x==null?'—':(x*100).toFixed(1)+'%',signed=x=>x==null?'—':(x>0?'+':'')+pct(x);
const num=x=>Number(x||0).toLocaleString('zh-CN',{maximumFractionDigits:2});
const compact=x=>x>=1e8?(x/1e8).toFixed(2)+'亿':x>=1e4?(x/1e4).toFixed(2)+'万':num(x);
const right=x=>x===0||x==='Call'?'Call':'Put',rightName=x=>right(x)==='Call'?'看涨期权':'看跌期权';
function node(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function time(iso,full=false){if(!iso)return '整段汇总';return new Intl.DateTimeFormat('zh-CN',{timeZone:el('zone').value,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',...(full?{second:'2-digit',fractionalSecondDigits:3}:{}),hourCycle:'h23'}).format(new Date(iso));}
function options(id,values,labels){const s=el(id),old=s.value;s.replaceChildren();for(const v of values){const o=node('option',labels?labels(v):v==='*'?'全部':v);o.value=v;s.append(o);}if(values.map(String).includes(old))s.value=old;}
function metrics(a){if(a.metrics)return a.metrics;const total=a.buy+a.sell+a.unknown+(a.mid||0),net=a.buy-a.sell,c=a.buy+a.sell;return {total,tendency:c?net/c:null,coverage:total?(c+(a.mid||0))/total:null,lower:total?(net-a.unknown)/total:null,upper:total?(net+a.unknown)/total:null,errorTolerance:total?Math.max(0,Math.abs(net)-a.unknown)/(2*total):null};}
const empty=()=>({buy:0,sell:0,mid:0,unknown:0,unknownPremiums:{},unknownCounts:{}});
function amounts(r){return el('alignment').value==='Consensus'?(r.consensus[el('method').value]||empty()):(r.scenarios[el('scenario').value]||empty());}
function timing(r){const method=el('method').value;const scenarios=data.settings.scenarios.filter(s=>s.method===method&&(s.offsetMs!=null||s.maximumAgeMs===-1));const values=scenarios.map(s=>r.scenarios[s.id]).filter(Boolean).map(a=>metrics(a).tendency).filter(v=>v!=null);const total=metrics(r.primary).total;return {low:values.length?Math.min(...values):null,high:values.length?Math.max(...values):null,count:values.length,conflict:total?(r.timeConflictPremiums[method]||0)/total:null};}
function popup(title,content){el('dialog-title').textContent=title;el('detail').replaceChildren();if(typeof content==='string')el('detail').append(node('p',content,'explanation'));else el('detail').append(content);if(!el('dialog').open)el('dialog').showModal();}
el('close').onclick=()=>el('dialog').close();el('dialog').addEventListener('click',e=>{if(e.target===el('dialog'))el('dialog').close();});
for(const b of document.querySelectorAll('[data-help]'))b.onclick=e=>{e.preventDefault();popup(...help[b.dataset.help]);};
function reasonInfo(key){return catalog.get(key)||catalog.get('UNSPECIFIED');}
function showReason(key,amount,count,a){const r=reasonInfo(key),m=a?metrics(a):null,content=node('div');content.append(node('p',r.explanation+'\n\n例子：'+r.example+(m?'\n\n本行：'+num(amount)+' 美元 · '+num(count)+' 笔\n占未知：'+pct(a.unknown?amount/a.unknown:null)+'；占全部已观察权利金：'+pct(m.total?amount/m.total:null):''),'explanation'));if(key==='UNRESOLVED_CANDIDATE'&&a)appendUnresolved(content,a);else content.append(node('p','技术原因码：'+key,'small'));popup(r.code+' · '+r.label,content);}
function appendUnresolved(parent,a){
 const groups=Object.values(a.unresolvedGroups||{}).sort((x,y)=>y.premium-x.premium),total=a.unknownPremiums?.UNRESOLVED_CANDIDATE||0;
 parent.append(node('h3','U25 里面，究竟卡在哪里？'));
 if(!groups.length){parent.append(node('p',total?'此报告没有二级证据，请使用新版分析器重新分析原始文件。':'本行没有 U25。','muted'));return;}
 parent.append(node('p','按“原因组合”划分，每笔只计一次，以下占比相加为 100%（分母是 U25 权利金）。多个原因同时出现时单列组合，不把同一笔钱重复算给每个原因。点击每组，继续看说明与真实报价。','explanation'));
 for(const g of groups){const box=node('details',null,'u25-group'),summary=node('summary');const label=g.reasons.map(k=>reasonInfo(k).code+' '+reasonInfo(k).label).join(' ＋ ');summary.append(node('span',label),node('strong',pct(total?g.premium/total:null)));box.append(summary);
 const bar=node('div',null,'u25-share'),fill=node('span');fill.style.width=(total?g.premium/total*100:0)+'%';bar.append(fill);box.append(bar);
 box.append(node('p',num(g.premium)+' 美元 · '+num(g.events)+' 笔 · 占全部已观察权利金 '+pct(metrics(a).total?g.premium/metrics(a).total:null)+(g.reasons.length>1?'。这是同一笔成交涉及多个原因的组合，不是几笔成交相加。':''),'small'));
 for(const key of g.reasons){const r=reasonInfo(key),line=node('p',null,'u25-cause'),mark=node('span',r.code,'reason-id');mark.style.backgroundColor=r.color;line.append(mark,node('strong',r.label),node('span','：'+r.explanation+' 例：'+r.example));box.append(line);}
 box.append(node('h4','真实成交示例（按接收顺序最多保留两笔，不代表全部成交）'));
 for(const e of g.examples){const example=node('details',null,'u25-example');example.append(node('summary',time(e.sourceUtc,true)+' · 成交价 '+num(e.price)+' · 权利金 '+num(e.premium)+' 美元'));
 example.append(node('p','原始序号 '+e.sequence+'；接收时间 '+time(e.receivedUtc,true)+'。下表只列实际参与一致性判断的候选；后到报价未使用。','small'));
 const scroll=node('div',null,'detail-scroll');appendTable(scroll,['候选报价','候选时刻','买价 / 卖价','分类结果','不能判断的原因'],e.candidates.map(c=>[c.alignment==='Latest'?'接收时最新报价':'源时间 '+c.alignment.replace('Source','')+' 毫秒',time(c.targetUtc,true),(c.bid==null?'未收到':num(c.bid))+' / '+(c.ask==null?'未收到':num(c.ask)),c.sign>0?'偏买':c.sign<0?'偏卖':['LOCKED_QUOTE','MIDPOINT_UNKNOWN','MID_TIME_AGREE'].includes(c.reason)?'Mid 中性':'未知',c.sign===0&&!['LOCKED_QUOTE','MIDPOINT_UNKNOWN','MID_TIME_AGREE'].includes(c.reason)?reasonInfo(c.reason).code+' '+reasonInfo(c.reason).label:'—']));example.append(scroll);box.append(example);}
 parent.append(box);}
}
for(const r of data.reasons){const b=node('button',null,'legend-item'),s=node('span',null,'swatch');s.style.backgroundColor=r.color;b.append(s,node('span',r.code+' '+r.label));b.onclick=()=>showReason(r.key);el('legend').append(b);}
function strikes(){const values=[...new Set(all.filter(r=>el('ticker').value==='*'||r.contract.ticker===el('ticker').value).map(r=>r.contract.strikeUsd))].sort((a,b)=>a-b);options('strike',['*',...values]);}
function scenarios(){const mode=el('alignment').value,method=el('method').value,previous=data.settings.scenarios.find(s=>s.id===el('scenario').value);el('scenario').disabled=mode==='Consensus';if(mode==='Consensus')options('scenario',['consensus'],()=> '全部可行候选 · 无年龄上限');else{const ss=data.settings.scenarios.filter(s=>s.method===method&&(mode==='Latest'?s.offsetMs==null:s.offsetMs!=null));options('scenario',ss.map(s=>s.id),id=>{const s=ss.find(x=>x.id===id);return mode==='Latest'?(s.maximumAgeMs<0?'不设报价年龄上限':s.maximumAgeMs+' 毫秒内报价'):'源时间 '+(s.offsetMs>=0?'+':'')+s.offsetMs+' 毫秒';});const keep=ss.find(s=>mode==='Latest'?s.maximumAgeMs===(previous?.offsetMs==null?(previous?.maximumAgeMs??-1):-1):s.offsetMs===(previous?.offsetMs??0));if(keep)el('scenario').value=keep.id;}
el('mode-note').textContent=mode==='Consensus'?'一致性模式：至少两个源时间候选可行，所有必要候选都能判断且同向才分类。各方法使用同一规则；报价可能是同一状态，不算独立证据。':mode==='Latest'?'单场景模式：只使用接收成交前的最后报价。报价年龄是敏感性实验参数，不是官方有效期。':'单场景模式：按选定偏移重建历史报价。不使用成交到达之后的报价；偏移是实验假设，不是已测得的延迟。';}
function filtered(ignoreBucket=false){return all.filter(r=>(el('ticker').value==='*'||r.contract.ticker===el('ticker').value)&&(el('strike').value==='*'||r.contract.strikeUsd===Number(el('strike').value))&&(el('right').value==='*'||right(r.contract.right)===el('right').value)&&r.scope===el('scope').value&&r.intervalMinutes===Number(el('interval').value)&&(ignoreBucket||el('bucket').value==='*'||(r.startUtc||'total')===el('bucket').value));}
function buckets(){options('bucket',['*',...[...new Set(filtered(true).map(r=>r.startUtc||'total'))].sort()],v=>v==='*'?'全部时间桶':v==='total'?'整段汇总':time(v));}
function stack(a){const m=metrics(a),bar=node('div',null,'bar');if(!m.total)return bar;for(const [value,cls,label] of [[a.buy,'buy','偏买'],[a.sell,'sell','偏卖'],[a.mid||0,'mid','Mid 中性'],[a.unknown,'unknown','未知']]){const seg=node('span',null,cls);seg.style.width=(value/m.total*100)+'%';seg.title=label+' '+num(value)+' 美元 · '+pct(value/m.total);bar.append(seg);}return bar;}
function range(low,high){const track=node('div',null,'range-track');if(low!=null&&high!=null){const s=node('span',null,'range-span');s.style.left=((low+1)*50)+'%';s.style.width=((high-low)*50)+'%';track.append(s);}return track;}
function unknownBar(a){const box=node('div');if(!a.unknown){box.append(node('span',metrics(a).total?'无未知':'无成交样本','muted'));return box;}const bar=node('div',null,'bar unknown-bar'),entries=Object.entries(a.unknownPremiums||{}).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);for(const [key,v] of entries){const r=reasonInfo(key),b=node('button');b.style.width=(v/a.unknown*100)+'%';b.style.backgroundColor=r.color;b.title=r.code+' '+r.label+' · 占未知 '+pct(v/a.unknown);b.setAttribute('aria-label',b.title);b.onclick=()=>showReason(key,v,a.unknownCounts[key]||0,a);bar.append(b);}box.append(bar,node('div',entries.slice(0,2).map(([k,v])=>reasonInfo(k).code+' '+pct(v/a.unknown)).join(' · '),'reason-caption'));return box;}
function td(tr){const n=node('td');tr.append(n);return n;}
function appendTable(parent,headers,rows){const t=node('table',null,'detail-table'),h=node('tr');for(const title of headers)h.append(node('th',title));const head=node('thead');head.append(h);t.append(head);const body=node('tbody');for(const values of rows){const row=node('tr');for(const v of values)row.append(node('td',v));body.append(row);}t.append(body);parent.append(t);}
function detail(r){const a=amounts(r),m=metrics(a),content=node('div');content.append(node('p',methods[el('method').value]+' · '+el('alignment').selectedOptions[0].textContent+' · '+(r.session==='RTH'?'常规交易时段':'全球交易时段'),'muted'));
const badges=node('div',null,'detail-badges');for(const q of r.quality)badges.append(node('span',quality[q]||q));if(!r.assessable)badges.append(node('span','证据不足：以下压力结果只作算术参考'));content.append(badges);
content.append(node('h3','未知原因明细'));appendTable(content,['编号 / 原因','权利金（美元）','笔数','占未知','占全部'],Object.entries(a.unknownPremiums||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=>[reasonInfo(k).code+' '+reasonInfo(k).label,num(v),num(a.unknownCounts[k]||0),pct(a.unknown?v/a.unknown:null),pct(m.total?v/m.total:null)]));
if(a.unknownPremiums?.UNRESOLVED_CANDIDATE){const more=node('details',null,'u25-section');more.append(node('summary','展开 U25 的具体原因与真实报价'));appendUnresolved(more,a);content.append(more);}
content.append(node('h3','额外误判压力'));appendTable(content,['假设有多少总权利金判反','最不利方向范围','严格保持方向？'],[.01,.02,.05].map(p=>{const lo=m.lower==null?null:Math.max(-1,m.lower-2*p),hi=m.upper==null?null:Math.min(1,m.upper+2*p);return[pct(p),lo==null?'—':signed(lo)+' 至 '+signed(hi),!r.assessable?'质量不足，不作判定':lo==null?'没有样本':lo>0||hi<0?'通过':'未通过（含触零）'];}));
content.append(node('h3','数据覆盖与集中度'));appendTable(content,['项目','结果'],[['可识别成交',num(r.events)+' 笔'],['成交量累计对账比例',pct(r.reconciliationVolumeCoverage)],['未被明细解释的可比较成交量',r.unexplainedVolume==null?'无法计算':num(r.unexplainedVolume)],['累计权利金差额',r.premiumDifference==null?'无法计算':num(r.premiumDifference)],['最大单笔 / 前五笔权利金占比',pct(r.largestFraction)+' / '+pct(r.topFiveFraction)]]);
content.append(node('h3','同一方法的全部时间与年龄对照'));const wrap=node('div',null,'detail-scroll');appendTable(wrap,['场景','倾向','分类覆盖','未知权利金'],data.settings.scenarios.filter(s=>s.method===el('method').value).map(s=>{const v=r.scenarios[s.id]||empty(),mm=metrics(v);return[s.offsetMs==null?'最新 / '+(s.maximumAgeMs<0?'无年龄上限':s.maximumAgeMs+' 毫秒'):'源时间 '+(s.offsetMs>=0?'+':'')+s.offsetMs+' 毫秒',signed(mm.tendency),pct(mm.coverage),num(v.unknown)];}));content.append(wrap,node('p','逐笔证据：同目录 decisions-*.jsonl。按合约编号 '+r.contract.conId+'、成交口径和源时间定位；其中保留原始序号、候选报价引用及原因码。','footnote'));popup(r.contract.ticker+' '+r.contract.strikeUsd+' '+rightName(r.contract.right)+' · '+time(r.startUtc),content);}
function render(){const rows=filtered();page=Math.min(page,Math.max(0,Math.ceil(rows.length/pageSize)-1));el('rows').replaceChildren();el('summary').replaceChildren();el('count').textContent=rows.length+' 个'+(el('interval').value==='0'?'合约汇总':'合约时间桶');el('page').textContent=(page+1)+' / '+Math.max(1,Math.ceil(rows.length/pageSize));el('prev').disabled=page===0;el('next').disabled=(page+1)*pageSize>=rows.length;el('empty').hidden=rows.length!==0;
let total=0,classified=0,unknown=0,conflicts=0;for(const r of rows){const a=amounts(r);total+=metrics(a).total;classified+=a.buy+a.sell+(a.mid||0);unknown+=a.unknown;conflicts+=r.timeConflictPremiums[el('method').value]||0;}
for(const [label,value,caption] of [['已观察权利金',compact(total),'当前筛选 · 美元'],['已分类覆盖',pct(total?classified/total:null),'按权利金，不按笔数'],['仍未知的占比',pct(total?unknown/total:null),'未知原因可点击色条'],['时间冲突占比',pct(total?conflicts/total:null),'候选买卖相反 · 非误判率']]){const card=node('div',null,'metric-card');card.append(node('div',label,'label'),node('div',value,'value'),node('small',caption));el('summary').append(card);}
for(const r of rows.slice(page*pageSize,(page+1)*pageSize)){const a=amounts(r),m=metrics(a),t=timing(r),tr=node('tr');const identity=td(tr);identity.append(node('div',time(r.startUtc)+(r.endUtc?' — '+time(r.endUtc).split(' ').at(-1):''),'row-time'),node('div',r.contract.ticker+' '+r.contract.strikeUsd+' · '+rightName(r.contract.right),'row-contract'));const hint=node('div',num(r.events)+' 笔','small');if(!r.assessable){const tag=node('span','参考','row-hint');tag.title=r.quality.map(q=>quality[q]||q).join('；');hint.append(tag);}identity.append(hint);
const flow=td(tr);flow.append(node('strong',compact(m.total)),stack(a),node('small','买 '+compact(a.buy)+' / 卖 '+compact(a.sell)+' / Mid '+compact(a.mid||0),'small'));
td(tr).append(node('span',signed(m.tendency),'big '+(m.tendency>0?'positive':m.tendency<0?'negative':'muted')));
const coverage=td(tr);coverage.append(node('span',pct(m.coverage),'big'));const coverageBar=node('div',null,'bar');coverageBar.style.width='72px';const fill=node('span',null,'buy');fill.style.width=((m.coverage||0)*100)+'%';coverageBar.append(fill);coverage.append(coverageBar,node('small','买卖方向 '+pct(m.total?(a.buy+a.sell)/m.total:null),'small'));
const bound=td(tr);bound.append(node('span',m.lower==null?'—':signed(m.lower)+' 至 '+signed(m.upper),'range-label'),range(m.lower,m.upper),node('small',m.lower==null?'没有样本':m.lower>0?'未知全反向仍偏买':m.upper<0?'未知全反向仍偏卖':'未知足以改变方向','small'));
const timingCell=td(tr);timingCell.append(node('span',t.low==null?'—':signed(t.low)+' 至 '+signed(t.high),'range-label'),range(t.low,t.high),node('small','冲突 '+pct(t.conflict)+' · '+t.count+'/6 场景可计算','small'));
td(tr).append(unknownBar(a));const tolerance=td(tr);tolerance.append(node('strong',pct(m.errorTolerance)),node('small',r.assessable?'临界值不算通过':'仅算术参考','small'));const button=node('button','···','icon-button');button.title='查看此桶详情';button.setAttribute('aria-label','查看 '+r.contract.ticker+' '+r.contract.strikeUsd+' 时间桶详情');button.onclick=()=>detail(r);td(tr).append(button);el('rows').append(tr);}}
el('outside').disabled=!data.outside;el('outside').onchange=()=>{const source=el('outside').checked?data.outside:data;all=[...source.totals,...source.buckets];page=0;render();};
options('ticker',['*',...new Set(all.map(r=>r.contract.ticker))]);options('right',['*','Call','Put'],v=>v==='*'?'全部':v==='Call'?'看涨期权（Call）':'看跌期权（Put）');strikes();scenarios();buckets();render();
for(const id of ['ticker','strike','right','scope','interval','method','alignment','scenario','bucket','zone'])el(id).onchange=()=>{page=0;if(id==='ticker')strikes();if(id==='method'||id==='alignment')scenarios();if(!['bucket','method','alignment','scenario'].includes(id))buckets();render();};
el('prev').onclick=()=>{page--;render();};el('next').onclick=()=>{page++;render();};el('preset').onclick=()=>{el('outside').checked=false;all=[...data.totals,...data.buckets];el('method').value='Midpoint';el('alignment').value='Consensus';scenarios();page=0;render();};
})();
