(function (root) {
  'use strict';
  const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
  const number = n => Number.isSafeInteger(n) && n >= 0 ? n.toLocaleString('en-US') : '—';
  function build(data) {
    if (data?.schema !== 'uw-page-collector/1' || !data.run || !Array.isArray(data.latest)) throw Error('不是有效的 UW 采集数据包');
    const run = data.run, zone = run.config.timezone;
    const stamp = value => {
      if (!value || !Number.isFinite(Date.parse(value))) return '未记录';
      return new Intl.DateTimeFormat('zh-CN', { timeZone: zone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).format(new Date(value));
    };
    const rows = [...data.latest].sort((a,b) => String(b.bucket.startUtc).localeCompare(String(a.bucket.startUtc)) || (b.volume ?? -1) - (a.volume ?? -1) || a.key.localeCompare(b.key));
    const reasonNames = Object.fromEntries((root.UwQuality?.reasons || []).map(([code, name]) => [code, name]));
    function rowHtml(r) {
      const id = r.identity, w = r.bucket, ba = r.ba, c = ba.counts;
      const valid = ba.status === 'RECONSTRUCTED' && c && ['bid','ask','neutral'].every(k => Number.isSafeInteger(c[k]) && c[k] >= 0) && c.bid + c.ask + c.neutral === r.volume;
      const kind = valid ? (ba.inference || ba.inferredSides?.length ? 'inferred' : 'resolved') : 'unknown';
      const status = { resolved: '比例还原', inferred: '缺段补算', unknown: '未能还原' }[kind];
      const reason = valid ? (ba.inference === 'single-full-width-assumes-omitted-sides-zero' ? '单侧实际宽度 100%，按满侧显示规则补零' : kind === 'inferred' ? '总量约束得到唯一剩余数量' : '三侧整数解唯一，合计校验通过') : reasonNames[ba.reason] || ba.reason || '数据校验未通过';
      const pct = k => r.volume > 0 ? c[k] / r.volume * 100 : 0;
      const bar = valid && r.volume > 0 ? `<div class="bar" aria-label="Bid ${c.bid}, Neutral ${c.neutral}, Ask ${c.ask}">${['bid','neutral','ask'].map(k => `<span class="${k}" style="width:${pct(k)}%" title="${k}: ${number(c[k])} / ${pct(k).toFixed(2)}%"></span>`).join('')}</div><div class="percent"><span>Bid ${(pct('bid')).toFixed(2)}%</span><span>Ask ${(pct('ask')).toFixed(2)}%</span></div>` : `<div class="unknown-bar">${valid ? '零成交量 · 比例不适用' : '数量未知 · 不绘制猜测比例'}</div>`;
      const field = name => r.raw?.fields?.find(f => f.name === name)?.text || '—';
      const bucketLabel = `${w.date} ${w.start}–${w.end}`;
      return `<tr data-ticker="${escape(id.ticker)}" data-right="${escape(id.right)}" data-bucket="${escape(bucketLabel)}" data-quality="${kind}" data-search="${escape([id.ticker,id.strike,id.right,id.expiry].join(' ').toLowerCase())}">
<td><b>${escape(w.start)}–${escape(w.end)}</b><small>${escape(w.date)}</small></td>
<td><b>${escape(id.ticker)}</b></td><td><b>${escape(id.strike)} <span class="${id.right === 'CALL' ? 'call' : 'put'}">${id.right === 'CALL' ? 'Call 看涨' : 'Put 看跌'}</span></b><small>到期 ${escape(id.expiry)}</small></td>
<td class="num">${number(r.volume)}</td><td class="num bid-text">${valid ? number(c.bid) : '—'}</td><td class="num ask-text">${valid ? number(c.ask) : '—'}</td><td class="num">${valid ? number(c.neutral) : '—'}</td>
<td class="chart">${bar}</td><td class="num">${escape(field('Premium'))}<small>UW 页面原文</small></td>
<td><span class="tag ${kind}">${status}</span><details><summary>核对详情</summary><p>${escape(reason)}</p><p>页面标签：${escape(r.raw?.label || '未显示')}<br>原始宽度 Bid / Neutral / Ask：${[r.raw?.bidPercent,r.raw?.neutralPercent,r.raw?.askPercent].map(v => escape(v ?? '无色段')).join(' / ')}</p><p>补算侧：${escape(ba.inferredSides?.join(', ') || '无')}<br>算法：${escape(ba.method || '未记录')}</p><p>首次保存：${escape(stamp(r.firstSeenUtc))}<br>此版本保存：${escape(stamp(r.capturedUtc))}<br>页面读取：${escape(stamp(r.pageReadUtc))}<br>版本号：${escape(r.revision)}<br>${r.timeState === 'FORMING' ? '记录时桶尚未结束' : '记录时桶已结束，仍可能被修订'}${r.volumeDecreased ? '<br>⚠ 本版总成交量比前版减少' : ''}</p><p>原始成交量：${escape(r.raw?.volume)}<br>平均成交价：${escape(field('Avg Fill'))}<br>多腿占比：${escape(field('% Multi'))}</p></details></td></tr>`;
    }
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'none'; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>UW 逐行核对 · ${escape(run.config.date)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f5f8;color:#21384b;font:14px 'Segoe UI','Microsoft YaHei',sans-serif}main{max-width:1700px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:28px;margin:8px 0}header small{letter-spacing:2px;color:#688092}p{line-height:1.8}.muted,small{color:#6f8393}small{display:block;font-size:12px;margin-top:5px}.notice{border-left:4px solid #208c87;background:#e6f2f0;padding:14px 18px;border-radius:8px;margin:22px 0}.filters{display:flex;flex-wrap:wrap;gap:16px;padding:20px;background:white;border:1px solid #dce5ec;border-radius:12px}label{display:grid;gap:8px;min-width:130px;color:#597486}select,input{font:inherit;border:1px solid #cbd9e2;background:#f8fafc;color:#233e52;border-radius:6px;padding:10px;max-width:360px}input{min-width:240px}.stats{display:flex;gap:30px;margin:22px 0;flex-wrap:wrap}.stats b{font-size:24px;margin-right:7px}.table-wrap{overflow:auto;border:1px solid #dce5ec;border-radius:12px;background:white}table{width:100%;border-collapse:collapse;min-width:1280px}th{background:#eaf0f5;color:#536e82;padding:16px 12px;text-align:left;white-space:nowrap}td{padding:17px 12px;border-top:1px solid #e5ecf1;vertical-align:top}tbody tr:nth-child(even){background:#f9fbfd}tbody tr:hover{background:#edf5f8}.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.chart{min-width:235px}.bar{display:flex;width:100%;height:24px;border-radius:5px;overflow:hidden;background:#e4e9ed}.bar span{display:block;height:100%}.bid{background:#ef4966}.ask{background:#2db494}.neutral{background:#c5cdd6}.bid-text,.put{color:#c43d58}.ask-text,.call{color:#078775}.percent{display:flex;justify-content:space-between;font-size:11px;margin-top:7px;color:#688092}.unknown-bar{padding:5px;border:1px dashed #a1b0bd;border-radius:5px;color:#71828f;font-size:12px}.tag{display:inline-block;padding:4px 8px;border-radius:4px;font-size:12px;white-space:nowrap}.resolved{background:#e0f2eb;color:#14795f}.inferred{background:#fff0d4;color:#926215}.unknown{background:#f3e6ea;color:#a13e58}summary{cursor:pointer;font-size:12px;color:#547187;margin-top:10px}details{max-width:270px;min-width:110px}details p{font-size:12px;overflow-wrap:anywhere}.legend{display:flex;gap:18px;margin:15px 0;font-size:12px}.legend i{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:5px}footer{margin-top:24px;color:#738694;font-size:12px;line-height:1.8}#empty{padding:30px;text-align:center}tr[hidden]{display:none}@media(max-width:700px){main{padding:16px}header{display:block}h1{font-size:23px}.stats{gap:15px}}@media print{.filters{display:none}main{padding:0}.table-wrap{overflow:visible}table{min-width:0;font-size:10px}.chart{min-width:140px}}
</style></head><body><main><header><div><small>WOLFMOSS / UW PAGE COMPARISON</small><h1>逐行核对，数字与色条放在一起。</h1><p class="muted">页面日期 ${escape(run.config.date)} · 时间均使用 ${escape(zone)} · 采集版本 ${escape(run.version)}</p></div><div>导出时间<small>${escape(stamp(data.exportedUtc))}</small></div></header>
<div class="notice">本报告展示本轮采集中<strong>每个合约时间桶最后保存的版本</strong>，不是同一时刻的整页截图，也不保证仍在 UW 当前结果列表内。请对齐日期、时间桶、到期日和合约再比较；UW 后续修订或变化可能导致差异。${run.status === 'RUNNING' ? '<br><strong>导出时采集仍在运行：这是截至导出时的快照。</strong>' : ''}</div>
<div class="filters"><label>品种<select id="ticker"><option value="">全部</option></select></label><label>时间桶<select id="bucket"><option value="">全部</option></select></label><label>期权类型<select id="right"><option value="">全部</option><option value="CALL">Call 看涨</option><option value="PUT">Put 看跌</option></select></label><label>还原状态<select id="quality"><option value="">全部</option><option value="resolved">比例还原</option><option value="inferred">缺段补算</option><option value="unknown">未能还原</option></select></label><label>合约搜索<input id="search" placeholder="例如 QQQ 740 或 2026-09-21"></label></div>
<div class="stats"><span><b id="total">0</b>条匹配记录</span><span><b id="known">0</b>条已还原</span><span><b id="inferred">0</b>条其中为补算</span><span><b id="unknown">0</b>条未知</span></div>
<div class="legend"><span><i class="bid"></i>Bid 红色</span><span><i class="neutral"></i>Neutral 灰色</span><span><i class="ask"></i>Ask 绿色</span><span>比例以该桶总成交量为分母；不是权利金加权。</span></div>
<div class="table-wrap"><table><thead><tr><th>时间桶</th><th>品种</th><th>合约 / 到期日</th><th class="num">区间成交量</th><th class="num">Bid 数量</th><th class="num">Ask 数量</th><th class="num">Neutral 数量</th><th>Interval B/A 对照</th><th class="num">权利金原文</th><th>还原状态</th></tr></thead><tbody>${rows.map(rowHtml).join('')}</tbody></table><div id="empty" hidden>没有符合筛选条件的记录</div></div>
<footer>Bid / Ask / Neutral 为页面比例还原结果，不是官方逐笔方向真值。补算可能使用单侧满宽约定，见每行详情。未知数量显示“—”，不会伪装成 0。权利金保留页面 K/M 原文，可能经过舍入。<br>本轮最后成功读取：${escape(stamp(run.lastPollUtc))} · 本地读取间断 ${number(run.gaps ?? 0)} 次 · 轮次 ${escape(run.id)}<br>此 HTML 可离线打开，不上传数据；它只用于核对最新版本。完整修订历史请保留 JSON 数据包。</footer></main>
<script>(function(){const rows=Array.from(document.querySelectorAll('tbody tr'));const ids=['ticker','bucket','right','quality'];for(const id of ['ticker','bucket']){const select=document.getElementById(id);for(const value of [...new Set(rows.map(r=>r.dataset[id]))]){const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option);}}function update(){let total=0,known=0,inferred=0;const words=document.getElementById('search').value.toLowerCase().trim().split(/\\s+/).filter(Boolean);for(const r of rows){const visible=ids.every(id=>!document.getElementById(id).value||r.dataset[id]===document.getElementById(id).value)&&words.every(w=>r.dataset.search.includes(w));r.hidden=!visible;if(visible){total++;if(r.dataset.quality!=='unknown')known++;if(r.dataset.quality==='inferred')inferred++;}}for(const [id,n]of Object.entries({total,known,inferred,unknown:total-known}))document.getElementById(id).textContent=n.toLocaleString();document.getElementById('empty').hidden=total!==0;}for(const id of ids)document.getElementById(id).addEventListener('change',update);document.getElementById('search').addEventListener('input',update);update();})();</script></body></html>`;
  }
  root.UwReport = { build };
  if (typeof module !== 'undefined') module.exports = root.UwReport;
})(globalThis);
