namespace WolfMoss.MarketData;

public enum MarketEventSource { Ib, Nightwatch }
public enum MarketEventKind { OptionOpenInterest, OptionCumulativeTrade, DealerHeatmap, DealerGex, ObservationBoundary }
public enum MarketTradeScope { NotApplicable, RegularTrades, AllTimeAndSales }
public enum MarketOptionRight { Call, Put }
[Flags]
public enum MarketEventQuality
{
    None = 0, SourceContinuityUnknown = 1, SourceTimeUnknown = 2, Delayed = 4,
    ObservationStart = 8, CounterReset = 16, OutOfOrder = 32, PartialCoverage = 64, SourceError = 128, ObservationEnd = 256
}
public enum MarketBoundaryReason { Unknown, SubscriptionEnded, SubscriptionReplaced, ConnectionClosed, SourceUnavailable, PermissionDenied, LineLimit, InvalidSourceSample }
public enum MarketEventAcceptance { Accepted, Disabled, Congested, Faulted }
public enum HistoricalReadStatus { Available, Disabled, Unavailable }

public sealed record MarketContractIdentity(long ConId, string Ticker, DateOnly Expiration,
    decimal Strike, MarketOptionRight Right, string TradingClass, string Exchange, decimal Multiplier);

// Intake may only know the provider's raw hours; unknown bounds are never invented.
public sealed record MarketTradingContext(DateOnly? SessionDate, DateTime? SegmentStartUtc,
    DateTime? SegmentEndUtc, string? ProviderHours, string? ProviderTimeZone);
public sealed record MarketCumulativeValues(long TotalVolume, decimal Vwap, decimal Multiplier,
    decimal? LastPrice, long? LastSize);
public readonly record struct MarketStrikeValue(decimal Strike, decimal Gex, string? NodeType = null,
    int? Rank = null, decimal? RelativeStrength = null);
public sealed record MarketDealerSummary(decimal? TotalGex, decimal? KingStrike, decimal? GammaFlip,
    decimal? CallWall, decimal? PutWall, decimal? MajorPositive, decimal? MajorNegative);
public sealed class MarketProviderValues
{
    public decimal Spot { get; }
    public IReadOnlyList<MarketStrikeValue> Strikes { get; }
    public MarketDealerSummary? Summary { get; }
    public DateTime BucketStartUtc { get; }
    public string? State { get; }
    public MarketProviderValues(decimal spot, IEnumerable<MarketStrikeValue> strikes,
        DateTime bucketStartUtc, MarketDealerSummary? summary = null, string? state = null)
    {
        var copy = strikes.Take(2049).ToArray();
        if (copy.Length > 2048) throw new ArgumentException("Provider frame too large", nameof(strikes));
        Spot = spot; Strikes = Array.AsReadOnly(copy); BucketStartUtc = bucketStartUtc; Summary = summary;
        State = state is "live" or "closed" or "stale" or "waiting" ? state : null;
    }
}

// Reserved audit metadata for FUTURE derived-result writers, not generated by intake.
public sealed record MarketAggregationContext(string AlgorithmVersion, string BucketMode,
    int IntervalMinutes, DateTime BucketStartUtc, DateTime BucketEndUtc,
    decimal AtmStrike, decimal LowestStrike, decimal HighestStrike, bool IsPartial);

// Immutable normalized input; never carries a key, account, request header or raw error.
// Unique identity: RecordingRunId + ReceiveSequence. SourceStreamId identifies a connection,
// ObservationGeneration identifies a subscription request (not a chart or its ATM).
public sealed record MarketEvent(int SchemaVersion, Guid RecordingRunId, long ReceiveSequence,
    MarketEventSource Source, MarketEventKind Kind, Guid SourceStreamId, long ConnectionGeneration,
    long ObservationGeneration, string Ticker, DateOnly? Expiration, MarketContractIdentity? Contract,
    DateTime? SourceUtc, DateTime ReceivedUtc, MarketTradingContext? Trading,
    MarketTradeScope TradeScope, MarketEventQuality Quality,
    long? OpenInterest = null, MarketCumulativeValues? Cumulative = null,
    MarketProviderValues? Provider = null, MarketAggregationContext? Aggregation = null, MarketBoundaryReason? Boundary = null);

public interface IMarketEventSink
{
    // Nonblocking admission only; Accepted is NOT a durable commit acknowledgement.
    MarketEventAcceptance TryPublish(MarketEvent value);
}

public sealed class DisabledMarketEventSink : IMarketEventSink
{
    public static DisabledMarketEventSink Instance { get; } = new();
    private DisabledMarketEventSink() { }
    public MarketEventAcceptance TryPublish(MarketEvent value) => MarketEventAcceptance.Disabled;
}

// Cumulative recording losses, separate from upstream/unsubscribed market gaps.
// Persist each revision transactionally with its batch; applies conservatively to the whole run.
public sealed record MarketRecordingLoss(long Revision, long Congested, long CaptureFailed, long WriteFailed,
    long UndeliveredOnStop, DateTime? LastLossUtc);
public sealed record MarketRecordingBatch(Guid RecordingRunId, IReadOnlyList<MarketEvent> Events,
    MarketRecordingLoss Loss);
public interface IMarketEventBatchWriter
{
    // Runs only on the sink worker. Implementations must honor cancellation and own their I/O resources.
    ValueTask WriteAsync(MarketRecordingBatch batch, CancellationToken cancellationToken);
}

public sealed record HistoricalQuery(MarketEventSource Source, MarketEventKind Kind,
    string Ticker, DateOnly? Expiration, long? ConId, DateTime FromUtc, DateTime ToUtc,
    MarketTradeScope? TradeScope = null, int Limit = 1000, string? ContinuationToken = null)
{
    public void Validate()
    {
        if (FromUtc.Kind != DateTimeKind.Utc || ToUtc.Kind != DateTimeKind.Utc || ToUtc <= FromUtc
            || string.IsNullOrWhiteSpace(Ticker) || Ticker.Length > 32 || Limit is < 1 or > 10000
            || ConId is <= 0 || ContinuationToken?.Length > 512)
            throw new ArgumentException("Invalid historical query");
    }
}
public sealed record HistoricalRecordingLoss(Guid RecordingRunId, MarketRecordingLoss Loss);
public sealed record HistoricalReadResult(HistoricalReadStatus Status, IReadOnlyList<MarketEvent> Events,
    IReadOnlyList<HistoricalRecordingLoss> RecordingLosses, string? ContinuationToken, bool SourceContinuityKnown);
public interface IHistoricalDataReader
{
    // [FromUtc, ToUtc) uses ReceivedUtc, not vendor bucket start. Pages must have stable ordering.
    ValueTask<HistoricalReadResult> ReadAsync(HistoricalQuery query, CancellationToken cancellationToken);
}
public sealed class DisabledHistoricalDataReader : IHistoricalDataReader
{
    public static DisabledHistoricalDataReader Instance { get; } = new();
    private static readonly HistoricalReadResult Empty = new(HistoricalReadStatus.Disabled,
        Array.Empty<MarketEvent>(), Array.Empty<HistoricalRecordingLoss>(), null, false);
    private DisabledHistoricalDataReader() { }
    public ValueTask<HistoricalReadResult> ReadAsync(HistoricalQuery query, CancellationToken cancellationToken)
    { cancellationToken.ThrowIfCancellationRequested(); query.Validate(); return ValueTask.FromResult(Empty); }
}
